@startuml
'https://plantuml.com/class-diagram

class App {
    start():void
}
class EditItemPageController{
}
class Item{
    ~String name
    ~BigDecimal value
    ~String serial_number
    ~int MAX_NAME_LENGTH

    +setName(String name):void
    +setValue(Long value):void
    +setSerial_number(String serial_number):void
    +getNameasString():String
    +getName():SimpleStringProperty
    +getValue():BigDecimal
}
class MainPageController{
}
class User{
    ObservableList<Item> inventory
    +Comparator<Item> nameComparator
    +Comparator<Item> valueComparator
    +Comparator<Item> serial_numberComparator

    +getInventory():ObservableList<Item>
    +sortName():void
    +sortValue():void
    +sortSerial():void
    +addItem():void
    +removeItem():void
    +editItem():void
}

@enduml